# Generated by Django 5.2 on 2025-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='executives/'),
        ),
        migrations.AlterField(
            model_name='personalityoftheweek',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
    ]
